#开发环境
spring:
  profiles: 
    include: dev-redis
  application: 
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server: 
  port: 8080
snowflake: 
  worker-id: 0
  datacenter-id: 0
