#开发环境
spring:
  profiles: 
    include: redis-dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0
    password: 
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
server: 
  port: 8081
snowflake: 
  worker-id: 0
  datacenter-id: 0
