eureka: 
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://172.16.0.13:8761/eureka/
    registry-fetch-interval-seconds: 5
  server:
    response-cache-update-interval-ms: 5000
    eviction-interval-timer-in-ms: 5000
spring:
  cloud:
    inetutils:
      preferred-networks:
      - 1.0.0.
      - 10.1.
  environment: prod
      