spring: 
  redis:
    host: 10.1.0.11
    port: 6379
    timeout: 5000
    database: 0
    password: Kase9SJW
    pool:
      max-active:  10
      max-wait: 10000
      max-idle: 10
      min-idle: 0