#UAT环境
spring:
  profiles: 
    include: uat-nacos, uat-redis
  application:
    name: gateway-token
  cloud: 
    inetutils: 
      preferred-networks: 10.
    loadbalancer: 
      retry: 
        enabled: true
server: 
  port: 8080
snowflake: 
  worker-id: 0
  datacenter-id: 1